message("-- SetUp GLFW CMake")
option(GLFW_BUILD_DOCS OFF)
option(GLFW_BUILD_EXAMPLES OFF)
option(GLFW_BUILD_TESTS OFF)
option(GLFW_INSTALL OFF)
add_subdirectory(${CMAKE_SOURCE_DIR}/ThirtParts/glfw)

set_target_properties(glfw PROPERTIES FOLDER 3rdparty) # Override standard 'GLFW3' subfolder

set(GLFW_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/ThirtParts/glfw/include)
set(GLFW_DEFINITIONS -DGLFW_INCLUDE_NONE)
set(GLFW_LIBRARIES ${GLFW_LIBRARIES} glfw)

set(SANDBOX_GLFW_LIBRARIES ${GLFW_LIBRARIES} CACHE INTERNAL "")
set(SANDBOX_GLFW_INCLUDES ${GLFW_INCLUDE_DIR} CACHE INTERNAL "")
set(SANDBOX_GLFW_DEFINES ${GLFW_DEFINITIONS} CACHE INTERNAL "")

message("---- GLFW Include: " ${SANDBOX_GLFW_INCLUDES})
message("---- GLFW Lib: " ${SANDBOX_GLFW_LIBRARIES})
message("---- GLFW Defines: " ${SANDBOX_GLFW_DEFINES})